apiVersion: v1
kind: ServiceAccount
metadata:
  name: neo4j-sa
  labels:
    app: neo4j
    neo4j-cluster: load-test-fwk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neo4j-service-reader
  labels:
    app: neo4j
    neo4j-cluster: load-test-fwk
rules:
  - apiGroups: [ "" ] # the core API group
    resources: [ "services" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neo4j-sa-to-service-reader-binding
  labels:
    app: neo4j
    neo4j-cluster: load-test-fwk
subjects:
  - kind: ServiceAccount
    name: neo4j-sa
roleRef:
  kind: Role
  name: neo4j-service-reader
  apiGroup: rbac.authorization.k8s.io