apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
    neo4j-cluster: load-test-fwk
    graphdb/cluster: load-test-fwk
    graphdb/role: load-test-fwk
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2004"
spec:
  clusterIP: None
  ports:
    - port: 7687
      name: bolt
    - port: 7474
      name: http
    - port: 2004
      name: metrics
      targetPort: 2004
      protocol: TCP
  selector:
    app: neo4j
{{ range $i := until (int $.Values.global.neo4j.instances) }}
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-discovery-{{ $i }}
  labels:
    neo4j-cluster: load-test-fwk
    graphdb/cluster: load-test-fwk
    graphdb/role: load-test-fwk
    app: neo4j
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: discovery
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: transaction
      port: 6000
      targetPort: 6000
      protocol: TCP
    - name: raft
      port: 7000
      targetPort: 7000
      protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: neo4j-{{ $i }}
{{- end -}}