load:
  neo4j:
    populatorProperties: # set these in specific values file if you do not want to inherit the values here
      - template.properties.location=/config/templates.properties
      - node.templates.location=/framework_data/files/templates
      - profile.files.location=/framework_data/files/load-profiles
      - cache.data.location=/framework_data/files/cache-data
      - query.cache.file.name=queryCache.log
      - transaction.properties.location=/config/transaction.properties
      - transaction.properties.present={{ $.Values.global.load.transactionPropertiesPresent }}
      - population.skip.allowed={{ not $.Values.global.neo4j.rebuild }}
      - concurrent.populator.workers={{ $.Values.global.populator.concurrent.workers }}
      - concurrent.populator.queue.threshold=1000
      - data-populator.minimum_instances=3
      - data-populator.max_batch_size=5000
      - data-populator.max_variance=100
      - data-populator.minimum_types=2
      - dps.suppress.variance=false
      - cud.cache.file.name=cudCache.log
      - runtime.creation.batch.size=1000
      # optimization - should be able to use this to limit the number of profiles we need to write to the DB
      # https://jira-oss.seli.wh.rnd.internal.ericsson.com/browse/TORF-629866
      - load.profiles={{ $.Values.global.load.profiles }}
    extendedProperties: # set these if you want to inherit the default values above
    populatorResources:
      cpu: 0 # set to non-zero if you want to request CPU
    templateProperties:
      ENM_23.3_Small_Cloud_Native:
        - nodeType=startId;noOfMibs
        - RadioNode_18_Q4_R57A02=1;160
        - RadioNode_18_Q3_R49A16=1;550
        - RBS_18_Q3_U_4_940=1;350
        - MGW_17A=1;15
        - EPG_16B_R13C=1;6
        - MTAS_1_5_20A=1;10
        - DSC_17B_R1A=1;10
        - SGSN_MME_16A_CP09_2=1;10
        - RNC_17A_V_8_1349=1;1
        - RNC_18_Q3_V_14_340=1;1
        - MINI_LINK_INDOOR=1;68
        - Router6672_R17B_GA=1;105
        - TCU02=1;56
        - SIU02=1;56
        - MINI_LINK_6352=1;15
        - ERBS_18_Q3_J_2_150=1;480
      ENM_24.2_Small_Cloud_Native: #CNIS N130
        - nodeType=startId;noOfMibs
        - DSC_17B_R1A=1;10
        - EPG_16B_16B_R13C=1;6
        - MGW_17A_C_1_267=1;15
        - MINI_LINK_6352_17B_M17B_6352_2_8=1;15
        - MINI_LINK_INDOOR_16A_M16A_TN_5_4FP_LH_1_6FP=1;3
        - MINI_LINK_INDOOR_17_Q4_M17_Q4_TN_6_1_LH_2_1=1;65
        - MTAS_1_5=1;10
        - RadioNode_20_Q4_20_Q4_R19A30=1;560
        - RadioNode_20_Q1_20_Q1_R88A07=1;160
        - RadioNode_20_Q2_20_Q2_R6A06=1;240
        - RadioNode_20_Q3_20_Q3_R13A40=1;480
        - RadioNode_21_Q2_R29A13_EPS=1;80
        - Router6672_R17B_GA=1;105
        - SGSN_MME_16A_CP09_2=1;10
        - SIU02=1;56
        - TCU02=1;56
      ENM_23.3_Extra_Large_Physical:
        - nodeType=startId;noOfMibs
        - MINI_LINK_669x=1;5000
        - EPG_1_6=1;25
        - SGSN_MME_1_54=1;16
        - SGSN_MME_1_57=1;20
        - SGSN_MME_1_60=1;44
        - RadioNode_21_Q2_R29A13_5GS=1;3720
        - RadioNode_21_Q3_R37A02_5GS=1;3840
        - RadioNode_21_Q4_R41A14_5GS=1;3720
        - RadioNode_23_Q1_R66A17_5GS=1;1
        - RadioNode_21_Q2_R29A13_EPS=1;2710
        - RadioNode_21_Q2_4877_712_573_EPS=1;810
        - RadioNode_21_Q3_R37A02_EPS=1;2560
        - RadioNode_21_Q4_R41A14_EPS=1;2640
        - RadioNode_23_Q1_R66A17_EPS=1;1
        - MTAS_1_2=1;5
        - MTAS_1_5=1;25
        - DSC_17B_R1A=1;15
        - DSC_17A=1;15
        - MGW_16A_C_1_214=1;25
        - MGW_17A_C_1_267=1;50
        - MGW_6_9_2_0=1;75
        - CCDM_0_8_1=1;40
        - EPG_0I_2_11=1;25
        - PCG_1_0=1;80
      ENM_23.11_Extra_Large_Cloud_Native:
        - nodeType=startId;noOfMibs
        - CCDM_0_8_1=1;40
        - DSC_17A_R1A=1;15
        - DSC_17B_R1A=1;15
        - EPG_0I_2_11=1;25
        - EPG_1_6=1;25
        - FRONTHAUL_6020_18_Q4=1;100
        - JUNIPER_MX_18_3R1=1;40
        - MGW_16A_C_1_214=1;25
        - MGW_17A_C_1_267=1;50
        - MGW_6_9_2_0=1;75
        - MINI_LINK_6352=1;750
        - MINI_LINK_669X_M18_Q2_669X_1_5=1;1750
        - MTAS_1_5=1;10
        - MTAS_1_7_MTAS_1_5=1;15
        - MTAS_1_2=1;5
        - PCG_1_0_20A=1;80
        - RadioNode_20_Q2_R6A06_5GS=1;3760
        - RadioNode_20_Q3_R13A40_5GS=1;3760
        - RadioNode_20_Q4_R19A30_5GS=1;3760
        - RadioNode_22_Q3_R55A08_5GS=1;1
        - RadioNode_18_Q4_R55A36_EPS=1;960
        - RadioNode_20_Q1_R88A07_EPS=1;2638
        - RadioNode_20_Q3_R13A40_EPS=1;2555
        - RadioNode_20_Q2_R6A06_EPS=1;2558
        - Router6274_R18Q4_GA=1;160
        - Router6675_R18Q4_GA=1;1200
        - SGSN_MME_1_18=1;44
        - SGSN_MME_16A_CP06=1;116
        - SGSN_MME_16A_CP09=1;20
      ENM_24_2_Extra_Large_Cloud_Native:
        - nodeType=startId;noOfMibs
        - SGSN_MME_1_18=1;44
        - MTAS_1_5=1;10
        - EPG_1_6=1;25
        - MTAS_1_7_MTAS_1_5=1;15
        - SGSN_MME_16A_CP06=1;16
        - SGSN_MME_16A_CP09=1;20
        - MTAS_1_2=1;5
        - DSC_17A=1;15
        - DSC_17B_R1A=1;15
        - MINI_LINK_6352_17B_M17B_6352_2_8=1;750
        - FRONTHAUL_6020_18_Q4=1;100
        - Router6675_R18Q4_GA=100000;1200
        - MINI_LINK_669x=1;1749
        - MINI_LINK_669X_M18_Q2_669X_1_5=1;1
        - Router6274_R18Q4_GA=1;160
        - RadioNode_1340_136_588_EPS=1;960
        - RadioNode_20_Q1_R88A07_EPS=1;2640
        - RadioNode_20_Q2_R6A06_5GS=1;3760
        - RadioNode_20_Q2_R6A06_EPS=1;2560
        - RadioNode_20_Q3_R13A40_5GS=1;3760
        - RadioNode_20_Q3_R13A40_EPS=1;2560
        - RadioNode_20_Q4_R19A30_5GS=1;3760
        - RadioNode_22_Q3_R55A08_5GS=1;1
        - RadioNode_22_Q3_R55A08_EPS=1;1
        - MGW_16A_C_1_214=1;25
        - MGW_17A_C_1_267=1;50
        - MGW_6_9_2_0=1;75
        - CCDM_0_8_1=1;40
        - EPG_0I_2_11=1;25
        - JUNIPER_MX_18_3R1=1;40
        - PCG_1_0=1;80
      ENM_24_3_Small_Cloud_Native:
        - nodeType=startId;noOfMibs
        - DSC_17B_R1A=1;10
        - EPG_16B_16B_R13C=1;6
        - MGW_17A_C_1_267=1;15
        - MINI_LINK_6352_17B_M17B_6352_2_8=1;15
        - MINI_LINK_INDOOR_16A_M16A_TN_5_4FP_LH_1_6FP=1;2
        - MINI_LINK_INDOOR_17_Q4_M17_Q4_TN_6_1_LH_2_1=1;66
        - MTAS_1_5=1;10
        - RadioNode_20_Q4_20_Q4_R19A30=1;560
        - RadioNode_20_Q1_20_Q1_R88A07=1;160
        - RadioNode_20_Q2_20_Q2_R6A06=1;240
        - RadioNode_20_Q3_20_Q3_R13A40=1;480
        - RadioNode_21_Q2_R29A13_EPS=1;80
        - Router6672_R17B_GA=1;105
        - SGSN_MME_16A_CP09_2=1;10
        - SIU02=1;56
        - TCU02=1;56
      ENM_24_3_Extra_Large_Cloud_Native:
        - nodeType=startId;noOfMibs
        - BSC_20.Q4_BSC-G20.Q4-R1BD-APG43L-3.7.0-R8C_GSM=1;22
        - BSC_21.Q1_6756-489-260_GSM=1;2
        - BSC_21.Q1_BSC-G21.Q1-R1BH-APG43L-4.0.0-R1D_GSM=1;24
        - BSC_21.Q2_BSC-G21.Q2-R1BM-APG43L-4.0.0-R1D_GSM=1;48
        - DSC_17A_17A-R1A_EPS=1;15
        - DSC_17B_17B-R1A_EPS=1;15
        - EPG_0I_2_11=1;25
        - EPG_1_6=1;25
        - ERBS_J.4.555_20.Q1-J.4.555_EPS=1;80
        - ERBS_J.4.604_20.Q1-J.4.604_EPS=1;640
        - ERBS_J.4.606_20.Q1-J.4.606_EPS=1;1280
        - ERBS_J.4.607_1885-528-914_EPS=1;560
        - MGW_16A_C_1_214=1;25
        - MGW_17A_C_1_267=1;50
        - MGW_6_9_2_0=1;75
        - MTAS_1_5=1;25
        - MTAS_1_2=1;5
        - RBS_U.4.1380_WRBS01.A09-U.4.1380_UMTS=1;2334
        - RNC_V.23.50_6418-181-501_UMTS=1;1
        - RNC_V.24.215_21.Q1-V.24.215_UMTS=1;1
        - RNC_V.25.213_21.Q2-V.25.213_UMTS=1;1
        - RadioNode_22_Q3_R55A08_5GS=1;1
        - RadioNode_20.Q4_20.Q4-R19A30_EPS=1;960
        - RadioNode_21.Q1_21.Q1-R23A35_EPS=1;1840
        - RadioNode_21_Q2_R29A13_EPS=1;4168
        - RadioNode_21_Q2_4877_712_573_EPS=1;552
        - RadioNode_22.Q3_22.Q3-R55A08_EPS=1;1
        - RadioNode_20.Q4_20.Q4-R19A30_GSM=1;1244
        - RadioNode_21.Q1_21.Q1-R23A35_GSM=1;2717
        - RadioNode_21.Q2_21.Q2-R29A13_GSM=1;1124
        - RadioNode_21.Q1_21.Q1-R23A35_UMTS=1;466
        - RadioNode_21.Q2_21.Q2-R29A13_UMTS=1;466
        - SGSN_MME_1_54=1;16
        - SGSN_MME_1_57=1;20
        - SGSN_MME_1_60=1;44
        - SIU02=1;3750
        - TCU02=1;3750
    # To be replaced by https://jira-oss.seli.wh.rnd.internal.ericsson.com/browse/TORF-624520.
    transactionProperties:
      ENM_23.3_Extra_Large_Physical:
        - appName=read;write
        - asrlservice=0;3015
        - said=7665549;10510510
        - apserv=0;45921
        - cellserv=0;152829
        - cmserv=4826319;127575
        - cmutilities=444;2044
        - mscmce=23408216;459436113
        - comecimpolicy=0;91039
        - dpcoordinator=0;136
        - ebsstreamtopology=0;34231
        - eventbasedclient=24103656;0
        - fileaccountservice=4;84407
        - fmalarmprocessing=0;12288809
        - fmhistory=24368;12900285
        - fmserv=27704;604528
        - kpiserv=97;353395
        - lcmserv=0;609827
        - msapgfm=0;493
        - mscm=219986;3612198
        - mscmip=0;9
        - msfm=994;1322
        - msnetlog=3326;2306
        - mspm=94480565;45130929
        - mspmip=29183397;19442
        - mssnmpcm=19231;22266297
        - mssnmpfm=394300;233779
        - nbfmsnmp=0;113
        - ncmagent=0;9118
        - nedoserv=0;707795
        - netex=6063;364495
        - netsecserv=248;0
        - nodecli=566307;0
        - pmrouterpolicy=0;248
        - pmserv=77804;276780
        - saserv=0;99075
        - secserv=0;324562
        - servicemanagement=0;1555029
        - shmcoreserv=33136;9177806
        - shmserv=41042;929063
        - supervc=0;6634
      ENM_23.3_Small_Cloud_Native:
        - appName=read;write
        - autoidservice=2765868;81733568
        - apserv=0;26072
        - cellserv=0;81919
        - cmserv=1028211;12819
        - cmutilities=0;2032
        - mscmce=967883;9760311
        - comecimpolicy=0;49966
        - eventbasedclient=1820779;0
        - fileaccountservice=0;57134
        - fmalarmprocessing=0;4642175
        - fmhistory=11927;4210926
        - fmserv=3178;23354
        - kpiserv=64;83358
        - lcmserv=0;50489
        - msapgfm=0;444
        - mscm=814592;42494540
        - mscmip=64430;766699
        - msfm=1704;1704
        - mskpirt=65757;104186
        - msnetlog=2736;1836
        - mspm=4794150;1037479
        - mspmip=1028321;251973
        - mssnmpcm=53367;437260
        - mssnmpfm=2494;2354
        - nbfmsnmp=0;58
        - nedoserv=0;325598
        - netsecserv=221;0
        - nodecli=2368;0
        - pmrouterpolicy=0;222
        - pmserv=28512;634692
        - saserv=0;116267
        - secserv=0;308747
        - ipsmserv=0;122102
        - shmcoreserv=3885;1348633
        - shmserv=4710;22172
        - supervc=0;960
  java:
    debugPort: 0
