apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-0-pv
  labels:
    app: neo4j
    neo4j-cluster: cluster
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc-data-neo4j-0
  labels:
    app: neo4j
    neo4j-cluster: cluster
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      neo4j-cluster: cluster
---
# Deleting a local hostPath volume does not ensure that its contents are removed. This utility job will prune any left-over data when re-creating the volume.
apiVersion: batch/v1
kind: Job
metadata:
  name: local-volume-prune-job
  labels:
    app: neo4j
spec:
  template:
    spec:
      containers:
        - name: local-volume-prune-job
          image: debian:latest
          command:
            - "/bin/bash"
            - "-c"
            - |
              rm -rf /data/*
              echo "Volumes pruned"
          volumeMounts:
            - name: neo4j-pvc-data-neo4j-0
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: neo4j-pvc-data-neo4j-0
          persistentVolumeClaim:
            claimName: neo4j-pvc-data-neo4j-0