apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-profile
  labels:
    app: neo4j
    neo4j-cluster: profiles
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data_profile"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: neo4j
    neo4j-cluster: profiles
  name: load-profiles
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  selector:
    matchLabels:
      neo4j-cluster: profiles
---
# Deleting a local hostPath volume does not ensure that its contents are removed. This utility job will prune any left-over data when re-creating the volume.
apiVersion: batch/v1
kind: Job
metadata:
  name: pop-volume-prune-job
  labels:
    app: neo4j
spec:
  template:
    spec:
      containers:
        - name: pop-volume-prune-job
          image: debian:latest
          command:
            - "/bin/bash"
            - "-c"
            - |
              rm -rf /data_profile/*
              echo "Volumes pruned"
          volumeMounts:
            - name: load-profiles
              mountPath: /data_profile
      restartPolicy: Never
      volumes:
        - name: load-profiles
          persistentVolumeClaim:
            claimName: load-profiles