apiVersion: v2

# Do not change the name of the chart without also changing it in eric-neo4j-load-test-fwk/charts/load-control/templates/_helpers.tpl
name: eric-neo4j-load-test-fwk
description: A Helm chart for the Neo4j Load Testing Framework

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

dependencies:
  - name: eric-neo4j-load-test-fwk-build-utility
    version: 0.1.1
  - name:  eric-neo4j-load-test-fwk-data-populator
    version: 0.1.1
  - name: eric-neo4j-load-test-fwk-load-control
    version: 0.1.1
  - name: eric-neo4j-load-test-fwk-load-generator
    version: 0.1.1
  - name: eric-neo4j-load-test-fwk-monitoring
    repository: file://optional/eric-neo4j-load-test-fwk-monitoring
    version: 0.1.1
    condition: global.monitoring.metricsEnabled
  - name: eric-neo4j-load-test-fwk-neo4j
    repository: file://optional/eric-neo4j-load-test-fwk-neo4j
    version: 0.1.1
    condition: global.neo4j.rebuild
  - name: eric-neo4j-load-test-fwk-data-validator
    repository: file://optional/eric-neo4j-load-test-fwk-data-validator
    version: 0.1.1
    tags:
      - validate
